from exercises.petting_zoo.cobra import Cobra
from exercises.petting_zoo.copperhead import Copperhead
from exercises.petting_zoo.donkey import Donkey
from exercises.petting_zoo.eel import Eel
from exercises.petting_zoo.garden_snake import Garden_Snake
from exercises.petting_zoo.goat import Goat
from exercises.petting_zoo.king_snake import King_Snake
from exercises.petting_zoo.llama import Llama
from exercises.petting_zoo.mallard import Mallard
from exercises.petting_zoo.milk_frog import Milk_Frog
from exercises.petting_zoo.rat_snake import Rat_Snake
from exercises.petting_zoo.rhinoceros import Rhinoceros
from exercises.petting_zoo.sloth import Sloth
from exercises.petting_zoo.slow_loris import Slow_Loris
from exercises.petting_zoo.tortoise import Tortoise

miss_fuzz = Llama("miss_fuzz", "fancy_llama")
mr_madof = Rat_Snake("mr_madof", "fancy_rat_snake")
mr_charm = Cobra("mr_charm", "fancy_cobra")
miss_goldy = Copperhead("miss_goldy", "fancy_copperhead")
mr_strong = Donkey("mr_strong", "fancy_donky")
ms_buzz = Eel("ms_buzz", "fancy_eel")
mr_flower = Garden_Snake("mr_flower", "fancy_garden_snake")
mr_curly = Goat("mr_curly", "fancy_goat")
mr_tiny = King_Snake("mr_tiny", "fancy_king_snake")
dr_quack = Mallard("dr_quack", "fancy_mallard")
miss_misty = Milk_Frog("miss_misty", "fancy_milk_frog")
mr_gentle = Rhinoceros("mr_gentle", "fancy_rhinoceros")
miss_chill = Sloth("miss_chill", "fancy_sloth")
mr_careful = Slow_Loris("mr_careful", "fancy_slow_loris")
miss_wise = Tortoise("miss_wise", "fancy_tortoise")
