from .cobra import Cobra
from .copperhead import Copperhead
from .donkey import Donkey
from .eel import Eel
from .Garden_Snake import Garden_Snake
from .goat import Goat
from .King_Snake import King_Snake
from .llama import Llama
from .mallard import Mallard
from .milk_frog import Milk_Frog
from .rat_snake import Rat_Snake
from .rhinoceros import Rhinoceros
from .sloth import Sloth
from .slow_loris import Slow_Loris
from .tortoise import Tortoise